local ItemsIndex = {
	Food = {
		{ id = "Apple", rarity = "Common", weight = 1 },
		{ id = "Bread", rarity = "Common", weight = 1 },
		{ id = "Cheese", rarity = "Rare", weight = 3 },
		{ id = "Pizza", rarity = "Epic", weight = 6 },
		{ id = "GoldenBurger", rarity = "Legendary", weight = 15 },
	},

	Classic = {
		{ id = "BloxCola", rarity = "Common", weight = 1 },
		{ id = "BloxyAward", rarity = "Epic", weight = 7 },
		{ id = "DominosCrown", rarity = "Legendary", weight = 20 },
	},
}

return ItemsIndex
